-- Angermund Transport ERP Supabase Schema
-- Run this in Supabase SQL Editor

create table if not exists trips (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  route text, driver text, truck text,
  km numeric default 0, rate numeric default 0,
  diesel_cost numeric default 0, tolls numeric default 0, permits_cost numeric default 0,
  food_money numeric default 0, border_cost numeric default 0, repairs numeric default 0, other_cost numeric default 0,
  status text default 'Completed'
);

create table if not exists fleet (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  truck_no text, trailer_no text, make_model text, driver text, status text,
  current_km numeric default 0, next_service_km numeric default 0,
  license_expiry date, roadworthy_expiry date, insurance_expiry date
);

create table if not exists drivers (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  name text, phone text, license_expiry date, pdp_expiry date, passport_expiry date, status text
);

create table if not exists diesel (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  date date, truck text, driver text, litres numeric default 0, amount numeric default 0, km numeric default 0, supplier text, slip_no text
);

create table if not exists permits (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  item text, owner text, type text, expiry_date date, cost numeric default 0, status text
);

create table if not exists payroll (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  date date, employee text, role text, basic_salary numeric default 0, days_worked numeric default 0, overtime_hours numeric default 0, advance numeric default 0, deductions numeric default 0
);

create table if not exists workers (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  date date, name text, site text, role text, status text, hours numeric default 0, overtime numeric default 0, rate numeric default 0, advance numeric default 0
);

create table if not exists maintenance (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  date date, truck text, issue text, cost numeric default 0, next_service_km numeric default 0, status text
);

create table if not exists tyres (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  date date, truck text, position text, brand text, serial_no text, cost numeric default 0, km_fitted numeric default 0, status text
);

create table if not exists workshop (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  date date, truck text, job_no text, description text, mechanic text, parts_cost numeric default 0, labour_cost numeric default 0, status text
);

create table if not exists fines (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  date date, driver text, truck text, type text, description text, amount numeric default 0, responsible_party text, status text
);

create table if not exists border_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  date date, truck text, driver text, border_post text, direction text, arrival_time text, release_time text, fees numeric default 0, delay_reason text
);

create table if not exists gps (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  email text, driver text, truck text, lat numeric, lng numeric
);

create table if not exists invoices (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  date date, client text, invoice_no text, route text, amount numeric default 0, paid numeric default 0, status text
);

create table if not exists profiles (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  email text, name text, role text default 'driver', status text default 'Active'
);

alter table trips enable row level security;
alter table fleet enable row level security;
alter table drivers enable row level security;
alter table diesel enable row level security;
alter table permits enable row level security;
alter table payroll enable row level security;
alter table workers enable row level security;
alter table maintenance enable row level security;
alter table tyres enable row level security;
alter table workshop enable row level security;
alter table fines enable row level security;
alter table border_logs enable row level security;
alter table gps enable row level security;
alter table invoices enable row level security;
alter table profiles enable row level security;

create policy "authenticated all trips" on trips for all to authenticated using (true) with check (true);
create policy "authenticated all fleet" on fleet for all to authenticated using (true) with check (true);
create policy "authenticated all drivers" on drivers for all to authenticated using (true) with check (true);
create policy "authenticated all diesel" on diesel for all to authenticated using (true) with check (true);
create policy "authenticated all permits" on permits for all to authenticated using (true) with check (true);
create policy "authenticated all payroll" on payroll for all to authenticated using (true) with check (true);
create policy "authenticated all workers" on workers for all to authenticated using (true) with check (true);
create policy "authenticated all maintenance" on maintenance for all to authenticated using (true) with check (true);
create policy "authenticated all tyres" on tyres for all to authenticated using (true) with check (true);
create policy "authenticated all workshop" on workshop for all to authenticated using (true) with check (true);
create policy "authenticated all fines" on fines for all to authenticated using (true) with check (true);
create policy "authenticated all border logs" on border_logs for all to authenticated using (true) with check (true);
create policy "authenticated all gps" on gps for all to authenticated using (true) with check (true);
create policy "authenticated all invoices" on invoices for all to authenticated using (true) with check (true);
create policy "authenticated all profiles" on profiles for all to authenticated using (true) with check (true);
